version: 0.2

phases:
  install:
    commands:
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - bash -c "source $HOME/.nvm/nvm.sh && nvm install 8 && npm i"
      - bundle install --path ./.bundle-gems
  build:
    commands:
      - bash -c "source $HOME/.nvm/nvm.sh && npm run build"
      - aws s3 sync --delete --acl public-read ./_site s3://flux-party-website/
      - aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
  post_build:
    commands: []
cache:
  paths:
    - node_modules
    - .bundle
    - .bundle-gems
